### ISSUE TITLE
scroll-button is hidden if exist bootstrap fixed navbar

### ISSUE THREAD

**Issue by WuglyakBolgoink** [padsbanger/angular-backtop#17]
in bootstap, if I use fixed bottom navbar, scroll-button is hidden. please fix Z-INDEX.

```css
#backtop {
    z-index: 9999;
}
```
